### PR TITLE
Feature docker

### PR DESCRIPTION
**Pull request by petski**
# Description

Add `Dockerfile` & `docker-compose` files, so that users can more easily use and deploy hyperglass.

Please note the `TODO`s in the Dockerfile. I don't have enough understanding of the project to oversee and/or fix all these `TODO`s at this moment. Despite the `TODO`s, all works as desired.

You could setup github-hooks to push a new version to https://hub.docker.com for each new version/tag.

# Related Issues and PRs

- https://github.com/checktheroads/hyperglass/issues/1
- https://github.com/checktheroads/hyperglass/issues/18
- https://github.com/checktheroads/hyperglass/pull/38

### CODE REVIEW

**Comment by forkwhilefork** [comment]
I've had a difficult time setting up hyperglass pretty much every time I've done it (or helped someone else do it), so a Docker image would be amazing.

**Comment by lst123** [comment]
I've finally managed to run Hyperglass in docker but only with Node 14. 
These files are little bit outdated. If somebody needs sources I can share.

**Comment by pl4nty** [comment]
@lst123 would be great if you can share sources :)

**Comment by waja** [comment]
Since there is GHCR is [available](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) it should be very easy to deploy images to GHCR via actions. So need to setup Docker Hub integration.

**Comment by monsieurpapa** [comment]
> I've finally managed to run Hyperglass in docker but only with Node 14. These files are little bit outdated. If somebody needs sources I can share.

Could you please share the Dockerfilevyou used? will be much appreciated

**Pull request closed without merging**
