### PR TITLE
feat: DoH ability to use custom servers

### PR DESCRIPTION
**Pull request by M0NsTeRRR**
# Related Issues
Fixes :  #254

### CODE REVIEW

**Comment by M0NsTeRRR** [comment]
I've removed the quick fix for #253, tests are expected to fail until it's rebased with hyperglass 2.0.2

**Comment by M0NsTeRRR** [comment]
@thatmattlove as an open-source contributor, I wanted to express my concern about how this PR was merged. The minimum courtesy when someone contributes is to keep the author credited as a thank you for their contribution. On GitHub, you have the right to edit my PR by default. If you need to add something, feel free to do so and then merge it. Of course, you have the final say as you are the maintainer.

I think (and hope) that you did this for convenience, and I trust that next time it will be merged properly.

PS : Thanks for your OSS project ;)

**Comment by thatmattlove** [comment]
Please refer to the [Contributing Policy](https://github.com/thatmattlove/hyperglass/blob/main/CONTRIBUTING.md), namely:

> Because I've been solo-maintaining and building hyperglass since around April 2019, I've become pretty particular about things that might seem trivial to someone just trying to help out. While I absolutely welcome development contributions, please don't be offended if pull requests are denied, or if I request things to be done a certain way.

I appreciate your willingness to contribute your time and effort to hyperglass, however, there were several reasons your PR was not merged:

1. I was already working on a solution after I saw #254, and didn't see your PR until those efforts were underway.
2. Your PR introduced a breaking change by removing the `name` field.
3. CI tests for your PR failed, though I have not looked into why.

In the future, if you plan to implement a fix for an issue you've raised, please indicate that intent in the issue so I know not to start working on it.

**Comment by M0NsTeRRR** [comment]
>  Because I've been solo-maintaining and building hyperglass since around April 2019, I've become pretty particular about things that might seem trivial to someone just trying to help out. While I absolutely welcome development contributions, please don't be offended if pull requests are denied, or if I request things to be done a certain way.

Sure, I understand, and I've read it, but you should not say contributions are welcome when you say right after that you can deny them just like that. You can deny it as you are the maintainer if we can't agree on how it must be done, and that's okay, but you can just request changes when someone has started working on it.

> I was already working on a solution after I saw https://github.com/thatmattlove/hyperglass/issues/254, and didn't see your PR until those efforts were underway.

No worries, it happens, but my PR was linked to the issue.

> Your PR introduced a breaking change by removing the name field.

Yes, you are right.

> CI tests for your PR failed, though I have not looked into why.

I've written in the next comment why; it's due to the "." bug. I've removed the temporary fix to get it merged easily. Rebasing on it is the only thing that was needed.

**Pull request closed without merging**
